version: "2"

linters:
  settings:
    gosec:
      excludes:
        - G202
        - G204
        - G302
        - G304
        - G306
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec
    - bodyclose
    - copyloopvar
