#!/usr/bin/env bash
set -euo pipefail

test -z "$(gofmt -l cmd internal pkg)"
go vet ./...
go test ./...
go test -race ./...
go test -run TestLeakLab ./...
./scripts/check-coverage.sh
govulncheck ./...
go build -trimpath ./cmd/agentfence
